### ISSUE TITLE
dump does not support sub collection.

### ISSUE THREAD

**Issue by ccfiel** [matsu0228/fsrpl#16]
I tried dump a collection with sub collection but the sub collection is not exported.

**Comment by matsu0228** [comment]
Thank you for your use and issue report.

We do not currently support recursive processing of subcollections.

If you want to handle subcollections with the current functionality, you will have to use shell scripts. (We would like to add this feature at some point).

An example of a shell script for handling subcollections (Japanese article)
https://qiita.com/mtskhs/items/65e66caa6dc9cd706c76#%E5%86%8D%E5%B8%B0%E7%9A%84%E3%81%AB%E3%82%B3%E3%83%94%E3%83%BC%E3%81%8C%E3%81 %A7%E3%81%8D%E3%81%AA%E3%81%84

**Comment by ccfiel** [comment]
Ok thanks! :)
